version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 'postgres'

  website:
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/one-note'
      - 'box:/box'
    stdin_open: true
    tty: true

  box:
    image: busybox
    volumes:
      - box:/box

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1025:25
      - 1080:80

volumes:
  postgres:
  box: