version: '3'

services:
  postgres:
    image: 'postgres:12'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 'postgres'

volumes:
  postgres: